# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metatag.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmetatag.proto\"@\n\x0c\x43ompressSpec\x12\x0e\n\x06\x65nable\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\x02\x12\x11\n\tmaxElapse\x18\x03 \x01(\x03\"\xd9\x01\n\x07MetaTag\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08showName\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x18\n\x04type\x18\x05 \x01(\x0e\x32\n.ValueType\x12\x0c\n\x04unit\x18\x06 \x01(\t\x12\r\n\x05range\x18\x07 \x01(\t\x12\x1f\n\x0c\x64\x65\x66\x61ultValue\x18\x08 \x01(\x0b\x32\t.RtdValue\x12\x0f\n\x07storage\x18\t \x01(\x08\x12\x1f\n\x08\x63ompress\x18\n \x01(\x0b\x32\r.CompressSpec\")\n\x0fMetaTagSequence\x12\x16\n\x04tags\x18\x01 \x03(\x0b\x32\x08.MetaTag\"\x92\x01\n\x08RtdValue\x12\x11\n\ttimeStamp\x18\x01 \x01(\x03\x12\x0f\n\x07quality\x18\x02 \x01(\x03\x12\x10\n\x06intVal\x18\x03 \x01(\x03H\x00\x12\x10\n\x06\x64\x62lVal\x18\x04 \x01(\x01H\x00\x12\x11\n\x07\x62oolVal\x18\x05 \x01(\x08H\x00\x12\x10\n\x06strVal\x18\x06 \x01(\tH\x00\x12\x10\n\x06\x62ytVal\x18\x07 \x01(\x0cH\x00\x42\x07\n\x05value\"4\n\nNamedValue\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x18\n\x05value\x18\x02 \x01(\x0b\x32\t.RtdValue\",\n\rValueSequence\x12\x1b\n\x06values\x18\x01 \x03(\x0b\x32\x0b.NamedValue\"*\n\x08RtdEvent\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"+\n\x11GatewayCoordinate\x12\x16\n\x0elocalTimeStamp\x18\x01 \x01(\x03\"C\n\x10ServerCoordinate\x12\x16\n\x0elocalTimeStamp\x18\x01 \x01(\x03\x12\x17\n\x0fserverTimeStamp\x18\x02 \x01(\x03*U\n\tValueType\x12\x0b\n\x07Unknown\x10\x00\x12\x0b\n\x07Integer\x10\x01\x12\n\n\x06\x44ouble\x10\x02\x12\x0b\n\x07\x42oolean\x10\x03\x12\n\n\x06String\x10\x04\x12\t\n\x05\x42ytes\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metatag_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VALUETYPE']._serialized_start=753
  _globals['_VALUETYPE']._serialized_end=838
  _globals['_COMPRESSSPEC']._serialized_start=17
  _globals['_COMPRESSSPEC']._serialized_end=81
  _globals['_METATAG']._serialized_start=84
  _globals['_METATAG']._serialized_end=301
  _globals['_METATAGSEQUENCE']._serialized_start=303
  _globals['_METATAGSEQUENCE']._serialized_end=344
  _globals['_RTDVALUE']._serialized_start=347
  _globals['_RTDVALUE']._serialized_end=493
  _globals['_NAMEDVALUE']._serialized_start=495
  _globals['_NAMEDVALUE']._serialized_end=547
  _globals['_VALUESEQUENCE']._serialized_start=549
  _globals['_VALUESEQUENCE']._serialized_end=593
  _globals['_RTDEVENT']._serialized_start=595
  _globals['_RTDEVENT']._serialized_end=637
  _globals['_GATEWAYCOORDINATE']._serialized_start=639
  _globals['_GATEWAYCOORDINATE']._serialized_end=682
  _globals['_SERVERCOORDINATE']._serialized_start=684
  _globals['_SERVERCOORDINATE']._serialized_end=751
# @@protoc_insertion_point(module_scope)
